# import numpy as np

# py -m pip install numpy

# import numpy as np

# salary = np.array([20000, 30000, 40000])

# print(salary*1.10)

# import numpy as np

# 4. Python List vs NumPy Array
# Feature	Python List	NumPy Array
# Speed	Slow	Fast
# Memory	High	Low
# Mathematical Operations	Difficult	Easy
# Data Handling	Flexible	Efficient
# Example 1: Addition

# list1 = [10, 20, 30]
# print(list1 + list1)

# import numpy as np

# arr = np.array([10,20,30])
# print(arr + arr)

# 5. Creating Arrays in NumPy
# 5.1 Creating 1D Array
# np.array()
# import numpy as np

# marks = np.array([85, 90, 78, 92])
# print(marks)

# Real World Example
# Monthly Sales:
# import numpy as np

# sales = np.array([12000, 15000, 18000, 20000])
# print(sales)

5.2 Creating 2D Array

